import { v4 as uuidv4 } from "uuid";

export const fashionData = [
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: "trousers",
    style: "glitter",
    brandName: "G-Star",
    color: "blue",
    material: "denim",
    image: "/images/00002-loewe-spring-2024-menswear-credit-gorunway (2).webp",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["trousers", "jacket", "jumper"],
    style: "casual",
    brandName: "Ralph Lauren",
    color: ["blue", "black", "white"],
    material: ["denim", "cotton"],
    image: "/images/6e449b6cc1680a825557d382ee4d4a75.jpg",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["shirt", "trousers"],
    style: "casual",
    brandName: "Nike",
    color: ["white", "beige"],
    material: ["stoff", "jersey"],
    image:
      "/images/00007-junya-watanabe-spring-2024-menswear-credit-gorunway.webp",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["shirt", "blouse", "trousers", "shoes", "shirt"],
    style: ["casual", "chic", "stripes"],
    brandName: ["Ralph Lauren", "G-Star", "Weekday"],
    color: ["yellow", "blue", "khaki", "light blue"],
    material: ["denim", "jersey", "silk"],
    image: "/images/9e6ca2ad1dec47b06965cafa1e0c7052.jpg",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["jumper", "trousers", "shirt"],
    style: ["casual", "evening", "chic"],
    brandName: ["Emporio Armani", "Guess"],
    color: ["beige", "khaki", "black"],
    material: ["leather", "jersey", "cotton"],
    image:
      "/images/00010-emporio-armani-spring-2024-menswear-credit-gorunway.webp",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["shorts", "shirt"],
    style: ["business casual", "chic", "sommer", "cool"],
    brandName: ["Emporio Armani", "Gucci"],
    color: ["transparent", "black"],
    material: ["cotton", "silk", "light", "mesh"],
    image: "/images/00036-bally-spring-2024-ready-to-wear-credit-gorunway.webp",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["shirt", "trousers"],
    style: ["evening", "chic", "cool chic"],
    brandName: ["Gucci", "Dolce & Gabbana"],
    color: "black",
    material: ["mesh", "velvet"],
    image: "/images/00039-saint-laurent-spring-2024-menswear-credit-brand.webp",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["teeth", "trousers", "blazer", "suit trousers"],
    style: ["chic", "business", "suit"],
    brandName: ["Prada", "Dolce & Gabbana", "Gucci"],
    color: "grey",
    material: "cotton",
    image: "/images/00046-prada-spring-2024-menswear-credit-gorunway.webp",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "top",
      "trousers",
      "wide leg",
      "dad jenas",
      "suit trousers",
    ],
    style: ["casual chic", "suit"],
    brandName: "Zara",
    color: ["white", "cream"],
    material: ["cotton", "jersey"],
    image: "/images/1715267324-the-renata-pant-706468.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: ["dress", "maxi dress", "maxi"],
    style: ["casual", "beach", "sommer", "cut out"],
    brandName: "H&M",
    color: ["cream", "beige"],
    material: "cotton",
    image:
      "/images/1715268534-screen-shot-2024-05-09-at-11-28-27-am-663ceba129b06.png",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: ["jogging trousers", "pants", "top", "crop top", "jogging"],
    style: "sport",
    brandName: "H&M",
    color: ["gray", "white"],
    material: "jersey",
    image:
      "/images/1715268788-screen-shot-2024-05-09-at-11-32-51-am-663ceca713c10.png",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: ["trousers", "pants", "top", "wide leg"],
    style: ["city", "chic", "stylish", "cool", "parachute", "cut out"],
    brandName: ["Guess", "Gucci", "Marc Jacobs"],
    color: ["white", "cream", "beige"],
    material: "cotton",
    image:
      "/images/amaka-hamelijnck-seen-wearing-white-top-pants-with-side-news-photo-1678848415.jpg",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["t-shirt", "coat", "jeans", "trousers", "wide leg"],
    style: ["casual", "straight", "city", "minimalistic", "cool"],
    brandName: ["Adidas", "Tommy Hilfiger", "Zara", "Mango"],
    color: ["black", "white"],
    material: "cotton",
    image: "/images/Bally-Spring-Summer-2024-Minimalist-Fashion-Trend-Men.jpg",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: ["coat", "jumpsuit", "trousers", "short", "pants"],
    brandName: "Dolce & Gabbana",
    color: ["beige", "gold"],
    material: ["lace", "cotton", "silk"],
    image:
      "/images/Dolce-Gabbana-Spring-Summer-2024-Sheer-Fashion-Trend-Men.jpg",
  },
  {
    id: uuidv4(),
    gender: ["male", "female"],
    clothingPiece: ["shorts", "jumper", "jacket", "shirt", "short pants"],
    style: ["jeans", "cool", "city"],
    brandName: ["Adidas", "Nike", "H&M"],
    color: ["white", "light blue", "blue"],
    material: ["denim", "cotton", "jersey", "jeans"],
    image: "/images/e6833c70da38405cac2b809e4a7ab905.webp",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: ["t-shirt", "crop top", "jeans", "trousers"],
    brandName: ["Zalando", "Zara", "Mango"],
    color: ["black", "light blue", "blue"],
    material: ["jeans", "denim", "jersey"],
    image:
      "/images/ellie-delphine-wears-a-black-with-brown-gold-blue-print-news-photo-1678847246.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: ["jumper", "shirt", "shorts"],
    style: ["summer", "sailor", "stripes", "old money"],
    brandName: ["Guess", "Tommy Hilfiger", "Mango"],
    color: ["cream", "blue", "white"],
    material: "cotton",
    image:
      "/images/emili-sindlev-is-seen-wearing-black-sunglasses-pearl-news-photo-1678846557.jpg",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: [
      "blues",
      "shirt",
      "trousers",
      "dungarees",
      "jeans",
      "jumper",
    ],
    style: ["business", "casual", "street"],
    brandName: ["Fendi", "Guess", "Zara"],
    color: ["beige", "khaki", "brown", "black"],
    material: ["leather", "denim", "jeans", "linen"],
    image: "/images/Fendi-Spring-Summer-2024-Workwear-Fashion-Trend-Men.jpg",
  },
  {
    id: uuidv4(),
    gender: "male",
    clothingPiece: [
      "suit",
      "suit pants",
      "trousers",
      "pants",
      "shirt",
      "jumper",
    ],
    style: ["business", "casual", "street", "cool"],
    brandName: ["Fendi", "Guess", "Zara"],
    color: "black",
    material: ["cotton"],
    image:
      "/images/Ferragamo-Spring-Summer-2024-Minimalist-Fashion-Trend-Men.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: ["maxi dress", "dress"],
    style: ["summer", "casual"],
    brandName: "Zara",
    color: "yellow",
    material: ["linen", "jersey", "cotton"],
    image:
      "/images/guest-is-seen-wearing-a-yellow-khaite-dress-outside-the-news-photo-1678847923.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "jeans",
      "trousers",
      "blazer",
      "crop",
      "crop blazer",
      "crop top",
      "pants",
    ],
    style: ["business", "chic", "summer", "casual"],
    brandName: ["Zara", "Mango", "H&M"],
    color: ["blue", "light blue"],
    material: ["denim", "jeans", "cotton"],
    image:
      "/images/guest-is-seen-wearing-blue-cropped-blazer-denim-jeans-news-photo-1678849449.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: ["trousers", "white leg", "bootcut", "dad jeans", "shirt"],
    style: ["casual", "business", "street chic"],
    brandName: "Zara",
    color: ["cream", "white", "black"],
    material: ["denim", "cotton", "jersey"],
    image:
      "/images/guest-wearing-white-pants-oversized-brown-bag-outside-cos-news-photo-1678848649.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "jeans",
      "denim",
      "white leg",
      "dad jeans",
      "bootcut",
      "crop top",
      "top",
      "blazer",
      "oversize blazer",
    ],
    style: ["street", "casual", "cool"],
    brandName: "Zara",
    color: ["blue", "beige"],
    material: ["denim", "jersey", "cotton"],
    image:
      "/images/guest-wears-a-beige-cropped-tank-top-a-beige-blazer-jacket-news-photo-1678847994.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "skirt",
      "maxi skirt",
      "top",
      "short top",
      "denim skirt",
      "body",
    ],
    style: ["street", "chic", "cool", "summer", "denim"],
    brandName: ["Zara", "Levi's"],
    color: ["blue", "black"],
    material: ["denim", "jersey"],
    image:
      "/images/guest-wears-a-black-halter-neck-tank-top-a-navy-blue-denim-news-photo-1678849601.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "white leg",
      "white trousers",
      "business trousers",
      "dead trousers",
      "bikini",
      "crop top",
      "blazer",
      "oversized blazer",
      "suit",
    ],
    style: ["street", "cool", "business casual"],
    brandName: "Zara",
    color: ["beige", "white", "cream"],
    material: "cotton",
    image:
      "/images/guest-wears-a-white-lace-front-ruffled-sleeves-blouse-a-news-photo-1678846692.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "skirt",
      "maxi skirt",
      "oversize blazer",
      "blazer",
      "bikini",
      "top",
      "crop top",
    ],
    style: ["street chic", "cool", "maxi denim skirt", "oversize"],
    brandName: "Zara",
    color: ["blue", "black", "white"],
    material: ["denim", "cotton", "jersey"],
    image:
      "/images/guest-wears-black-sunglasses-a-white-v-neck-cropped-tank-news-photo-1678847617.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "wide leg trousers",
      "business trousers",
      "t-shirt",
      "oversized t-shirt",
      "suit",
    ],
    style: ["street chic", "casual business"],
    brandName: "Yves Saint Laurent",
    color: ["beige", "khaki", "white"],
    material: "cotton",
    image:
      "/images/guest-wears-black-sunglasses-a-white-with-black-ysl-print-news-photo-1678848353.jpg",
  },
  {
    id: uuidv4(),
    gender: "female",
    clothingPiece: [
      "dad jeans",
      "wide leg trousers",
      "business trousers",
      "shirt",
      "t-shirt",
      "cardigan",
      "suit",
    ],
    style: ["street chic", "casual business", "cool"],
    brandName: "Yves Saint Laurent",
    color: ["beige", "white"],
    material: ["cotton", "denim"],
    image:
      "/images/guest-wears-brown-sunglasses-a-white-ribbed-wool-laces-news-photo-1678847420.jpg",
  },
];
